### ISSUE TITLE
Validator bounding volume and transform

### ISSUE THREAD

**Issue by phanemy** [CesiumGS/3d-tiles-validator#173]
Hello, i'm writing a 3Dtile generator from 3d mesh and I use the validator to check if my tiles are good. 

My first issue was to find the working validator, in master branch validator don't work, in validator-master branch same, the good one was in validator branch, maybe merge it into the master branch to make is utilisation more simple.

My second issue was related to the boundingBox, i don't know if it's coming from my compréhension of the 3d tile spécification, but  for me the bounding volume(box one) is in the same space as the tile and is affected by parents tiles transform and local, but with this idea the validator says my bounding box wasn't in parent box. After searching in utility.js file I find that boundingBox only use the local transform of is tile without parents transform. Is that normal or not? which philosophy is the good one.

Thanks for your answer.

**Comment by javagl** [comment]
It could be helpful to have an example tileset file that shows the problem. But in general, the `checkBoundingVolume` that you referred to is [only called for tile and the tile content](https://github.com/CesiumGS/3d-tiles-validator/blob/e84202480eb6572383008076150c8e52c99af3c3/validator/lib/validateTileset.js#L110). It does _not_ check wheter a child bounding volume is contained in the parent bounding volume, because this is not required by the specification, and often not the case. See https://github.com/CesiumGS/3d-tiles/blob/main/specification/README.md#bounding-volume-spatial-coherence for examples.

**Comment by javagl** [comment]
I'll close this due to inactivity (and the request is not perfectly clear either - and it referred to the "old" state of the validator anyhow). 

Some possible improvements for the bounding volume validation are tracked in https://github.com/CesiumGS/3d-tiles-validator/issues/233 .
