### ISSUE TITLE
3DTILES_content_gltf ?

### ISSUE THREAD

**Issue by bertt** [CesiumGS/3d-tiles-validator#282]
Hi, I'm getting the following error when validating a 1.1 tileset with GLB's and metadata:

```
EXTENSION_FOUND_BUT_NOT_USED - The extension '3DTILES_content_gltf' was found, but not declared in 'extensionsUsed'
```

Question: Is this error valid? What's the status of this 3DTILES_content_gltf extension?

**Comment by javagl** [comment]
This should not happen.

There are some open questions about the extension usage validation summarized in https://github.com/CesiumGS/3d-tiles-validator/issues/231 , and the current implementation may have to be reviewed, but the basic approach is:

- When the validator encounters tile content with the content type "glTF", then it tracks the `3DTILES_content_gltf` as one "**found**" extension
- At the end, it makes sure that all extensions that have been **found** are also declared in the `extensionsUsed` (and this should be the point where the validation error comes from)

- **But...** for 3D Tiles 1.1, it is no longer necessary to declare the `3DTILES_content_gltf` in the `extensionsUsed`, so even if it was found, it will be removed from the set of "found" extensions (that's ... a bit quirky, and marked as a [TODO referring to the above issue](https://github.com/CesiumGS/3d-tiles-validator/blob/94fc288452759a1c07948db421e84b433efa497e/src/validation/TilesetValidator.ts#L418
))

Looking at the code, I noticed that this _might_ be caused by a race condition: There should be an `await` at the beginning of [this line](https://github.com/CesiumGS/3d-tiles-validator/blob/94fc288452759a1c07948db421e84b433efa497e/src/validation/ContentDataValidator.ts#L133
). 

Maybe you want to try out whether this solves the issue for you. 
(But I'll add this in any case. And... we'll definitely have to enable some linting that detects these floating promises...)

Otherwise, it could be helpful if you could share that `tileset.json` or further information - e.g. does it use any `extensionsUsed`/`extensionsRequired` declarations? Does it declare the `asset.version === "1.1"`?

**Comment by bertt** [comment]
Ah yes that's it, fixed by changing asset.version  from 1.0 to 1.1! Thanks!

**Comment by javagl** [comment]
(When using `1.0`, then addding `3DTILES_content_gltf` to the `extensionsUsed` should also resolve the validation error, but since 1.1 is backward compatible, just declaring it as `1.1` and is most likely the better solution here)
