### ISSUE TITLE
Enable travis

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/3d-tiles-validator#7]
https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/pull/3#issuecomment-243894172

**Comment by lilleyse** [comment]
Travis is enabled but broken at the moment. I attempted to fix it here: https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/travis, but didn't get much further than that.

**Comment by shehzan10** [comment]
I think I have made a little more progress in my branch I did a while back. https://github.com/shehzan10/3d-tiles-tools/tree/travis and https://travis-ci.org/shehzan10/3d-tiles-tools/builds/224409856

The problem I had was with coveralls. Because the repo is setup as 3 distinct projects, coveralls always assumes that the current directory is the root. So all the 3 projects are going to generate coveralls that will then run into conflicts and the file links will not show up correctly. Here is the coveralls project link https://coveralls.io/builds/11181928.

Also has to xit one of the tests. Didn't look into it much.

**Comment by mramato** [comment]
I disabled travis for the time being because having it work has not been a priority and it's just a bunch of noise.

**Comment by javagl** [comment]
I consider travis to be one part of the somewhat broader question of deployment. Specificially: One part of the build process _might_ eventually be that the validator is deployed on a website with drag-and-drop support, similar to the glTF validator. The details and timeline for that have to be decided, but I wanted to mention it here to keep track of that.
